USE [master]
GO

/****** Object:  Database [BlocoNotas]    Script Date: 13/11/2016 16:00:11 ******/
CREATE DATABASE [BlocoNotas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlocoNotas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BlocoNotas.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BlocoNotas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BlocoNotas_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BlocoNotas] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlocoNotas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlocoNotas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlocoNotas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlocoNotas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlocoNotas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlocoNotas] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlocoNotas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlocoNotas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlocoNotas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlocoNotas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlocoNotas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlocoNotas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlocoNotas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlocoNotas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlocoNotas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlocoNotas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlocoNotas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlocoNotas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlocoNotas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlocoNotas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlocoNotas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlocoNotas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlocoNotas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlocoNotas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlocoNotas] SET  MULTI_USER 
GO

ALTER DATABASE [BlocoNotas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlocoNotas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlocoNotas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlocoNotas] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BlocoNotas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlocoNotas] SET  READ_WRITE 
GO

