USE [BlocoNotas]
GO

/****** Object:  Index [IDX_TEXTOID]    Script Date: 13/11/2016 16:45:28 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IDX_TEXTOID] ON [dbo].[TB_TEXTO]
(
	[TEXTO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

