//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TEXTO
    {
        public int TEXTO_PK { get; set; }
        public string TEXTO { get; set; }
        public string TEXTO_ID { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
    }
}
